language: objective-c
before_install:
  - gem install xcpretty --no-ri --no-rdoc
script:
  - set -o pipefail && xcodebuild build -osx_image: xcode7.3 -workspace "Example/SuperAwesome.xcworkspace" -scheme "SuperAwesome" -sdk iphonesimulator | xcpretty -c
